Color generator
Kennyc1012/TextDrawable pull request #3
Opened 2019-06-14 21:23 UTC by luca992

add the color generator in the original project back in ported to kotlin

also I updated the android sdk, kotlin, and gradle

2019-06-15 11:11 UTC, Kennyc1012 requested changes
Rebase your change onto master which removes the need for the sdk update commit

2019-06-15 11:14 UTC, Kennyc1012 requested changes

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +    private val mRandom: Random = Random(System.currentTimeMillis())
Do not use Hungarian notation, should  just be `random: Random`

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +        get() = mColors[mRandom.nextInt(mColors.size)]
Same here

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +        return mColors[Math.abs(key.hashCode()) % mColors.size]
Same here

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +        var DEFAULT: ColorGenerator = create(listOf(
Should be a val, not var

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +        var MATERIAL: ColorGenerator = create(listOf(
Same here

2019-06-15 11:14 UTC, Kennyc1012 commented on library/src/main/java/com/kennyc/textdrawable/ColorGenerator.kt
> +class ColorGenerator private constructor(private val mColors: List<Int>) {
Do not use Hungarian notation, should be `colors: List<Int>`

2019-06-18 01:32 UTC, luca992 commented
Made the fixes and rebased it onto master

2019-06-18 10:19 UTC, merged